/** Centralized API path constants. */
export const ENDPOINTS = {
  services: "/api/services",
  serviceBySlug: (slug: string) => `/api/services/${slug}`,
  psychologists: "/api/psychologists",
  psychologistById: (id: string) => `/api/psychologists/${id}`,
  patients: "/api/patients",
  appointments: "/api/appointments",
  appointmentById: (id: string) => `/api/appointments/${id}`,
  availability: "/api/availability",
  testimonials: "/api/testimonials",
  blogs: "/api/blogs",
  blogBySlug: (slug: string) => `/api/blogs/${slug}`,
  blogCategories: "/api/blogs/categories",
  resources: "/api/resources",
  faqs: "/api/faqs",
  notifications: "/api/notifications",
  messages: "/api/messages",
  assessments: "/api/assessments",
  assessmentResults: "/api/assessment-results",
  invoices: "/api/invoices",
  payments: "/api/payments",
  reviews: "/api/reviews",
  treatmentPlans: "/api/treatment-plans",
  reports: "/api/reports",
  emergencyContacts: "/api/emergency-contacts",
  contact: "/api/contact",
  search: "/api/search",
  stats: "/api/dashboard/stats",
} as const;